Repository openshift/backplane-tools, pull requests merged in 2023-11, with the labels that each got.

#20 Add initial installation instructions for v0.1.0
  README.md
Labels: approved, lgtm

#21 Fix invalid command reference in README
  README.md
Labels: approved, lgtm

#23 Installing aws, sould also expose aws_composer
  README.md
  cmd/list/available/available.go
  cmd/list/installed/installed.go
  cmd/list/list.go
  cmd/upgrade/upgrade.go
  pkg/tool/aws-cli/aws-cli.go
  pkg/tool/backplane-cli/backplane-cli.go
  pkg/tool/oc/oc.go
  pkg/tool/rosa/rosa.go
  pkg/tool/self/self.go
  pkg/tool/tool.go
  pkg/tool/yq/yq.go
Labels: approved, lgtm

#24 maintenance: add linting
  .golangci.yaml
  Makefile
  cmd/install/install.go
  cmd/remove/remove.go
  go.mod
  go.sum
  pkg/source/aws/aws.go
  pkg/source/github/github.go
  pkg/tool/awscli/aws-cli.go
  pkg/tool/backplane-cli/backplane-cli.go
  pkg/tool/oc/oc.go
  pkg/tool/ocm/ocm.go
  pkg/tool/osdctl/osdctl.go
  pkg/tool/rosa/rosa.go
  pkg/tool/self/self.go
  pkg/tool/tool.go
  pkg/tool/yq/yq.go
  pkg/utils/checksum.go
  pkg/utils/unarchive.go
Labels: approved, lgtm

#25 Fix Makefile to use tmp as golangci-lint cache
  Makefile
Labels: approved, lgtm

#26 Clarify installation steps
  README.md
Labels: approved, lgtm

#27 make sure checksum key isn't part of bigger one
  Makefile
  go.mod
  go.sum
  pkg/tool/backplane-cli/backplane-cli.go
  pkg/tool/oc/oc.go
  pkg/tool/osdctl/osdctl.go
  pkg/tool/rosa/rosa.go
  pkg/tool/self/self.go
  pkg/tool/yq/yq.go
  pkg/utils/utils.go
Labels: approved, lgtm, tide/merge-method-squash

#30 Use gh token to authenticate go-github client
  README.md
  go.mod
  go.sum
  pkg/source/github/github.go
Labels: approved, lgtm

#31 HOTFIX: override the OS name for 'darwin' runtimes
  pkg/tool/oc/oc.go
Labels: approved, lgtm

#34 Add .goreleaser.yml
  .goreleaser.yml
Labels: approved, lgtm, tide/merge-method-squash

#35 Update .goreleaser.yml to match previous releases
  .goreleaser.yml
Labels: approved, lgtm

#36 Fix goreleaser .OS case archives
  .goreleaser.yml
Labels: approved

#37 HOTFIX: Reference 'x86_64' instead of 'amd64' when self-upgrading
  pkg/tool/self/self.go
Labels: approved, lgtm

#38 Revert "HOTFIX: Reference 'x86_64' instead of 'amd64' when self-upgrading"
  pkg/tool/self/self.go
Labels: approved, lgtm

#40 Fix name template and whitespace issue
  .goreleaser.yml
Labels: approved, lgtm

#32 Updates AWS Wrapper script to fail fast if not on VPN
  pkg/tool/awscli/aws-cli.go
Labels: approved, lgtm
